### ISSUE TITLE
Dragging of crop area not possible

### ISSUE THREAD

**Issue by avril-verhaeghen** [standup75/cropme#17]
Hi,

I've noticed that when you put the cropme directive in any kind of element that has a float, position or something else of CSS positioning stuff, dragging for the crop area isn't working. 

You can still move around the crop area, but you can't for example resize it. This is kind of a big bummer. Are there plans to fix this soon? We're thinking of using it in our large scale project.

Thanks!

**Comment by arussellk** [comment]
I have what I believe to be the same problem in:
1. Chrome 39.0.2171.99 m
2. Firefox 35.0
3. IE 11.0.9600.17498
while on the demo site [here](http://standupweb.net/cropmedemo/#/).

If my browser window is scrolled below the top of the image, the crop-selection is not exactly with my cursor. The crop-selection moves where my cursor would be if my browser window were scrolled to the top.

To reproduce, I make my browser window too short, scroll down, and drag the box.

**Comment by divyenduz** [comment]
+1 :(

**Comment by piupiupiu** [comment]
+1

**Comment by standup75** [comment]
Check version 0.3.2 this has been addressed.
Please closed if verified

**Comment by arussellk** [comment]
It works on the demo site when before it did not. (http://standupweb.net/cropmedemo/#/)

Thanks for your work!

**Comment by divyenduz** [comment]
It works smoothly for me inside bootstrap modal as well. Finally, this looks resolved.
Thank you for all you effort on this one.

Regards
