### ISSUE TITLE
croppedImage getting blank while sending data on server

### ISSUE THREAD

**Issue by ashishthorat** [standup75/cropme#28]
I am trying to upload Croped Image On server but i got blank object of croppedImage on server , which is best way to upload crop file on server

$scope.$on("cropme:done", function(e, result, canvasEl) {
	console.log(result["croppedImage"]);
		$http.post(url, {'file': result["croppedImage"]})
		    .success(function(response){
		      
		    })
		   .error(function(responseg){
		     
		   });
		
	 });

**Comment by standup75** [comment]
I don't think using $http would work here because of serialization.
I would refer to the readme and follow the instruction to upload on to the server
