### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by blackotruck** [standup75/cropme#32]
Greettings, it's me again... Well, the other time i overwrite the template code to get bootstrap style buttons. Now, i don't want to mess with the code this time, but at the same time i want to be able to use a ui.bootstrap modal. The thing is, in the modal i put the buttons on the modal-footer, while hidding the original directive buttons... Now, how do i trigger the ok/cancel actions from the original buttons?

**Comment by sean-stanley** [comment]
I did exactly what you are describing in my project. The trick is to make a seperate controller for your modal and define ng-click functions for your buttons in it.

Those buttons should do two things each. They need to close or dismiss the modal, as well as accept or discard the cropped image.

Here is code to get you started.

```
$scope.ok = function() {
		$rootScope.$broadcast("cropme:ok");
};

$scope.cancel = function() {
	$rootScope.$broadcast("cropme:cancel");
	$modalInstance.dismiss('never mind');
};

$scope.$on("cropme:done", function(e, result, canvasEl) {
        $modalInstance.close(result.croppedImage);
});
```

Control Flow is important here. The reason `ok` only calls the cropme event is that if we told it to close the modal window at the same time, you might destroy the scope of the modal (and your cropped image) before it's finished being passed to whatever called the modal in the first place.

I hope that sorts you out.

**Comment by blackotruck** [comment]
Thanks for the quick response... i'll try it as soon as i can!

**Comment by standup75** [comment]
Can we close this one?

**Comment by blackotruck** [comment]
Yep, closing it
