### ISSUE TITLE
Is there a way to limit the file size of the original image ?

### ISSUE THREAD

**Issue by divyenduz** [standup75/cropme#35]
Is there a API right now to check the file size on upload ? 

Regards

**Comment by sean-stanley** [comment]
What exactly do you mean? Do you mean check the size of the original file once uploaded? Or the cropped one?

Are you looking for the size of the file on the user's file system? Or once it's been turned into a blob? They might differ slightly. 

I believe you can get the image size from the blob object after uploading is done.

**Comment by divyenduz** [comment]
Yes, I mean to restrict user from uploading if the file size is too long. Like there are pushed errors for dimensions. Is there a way ?

**Comment by standup75** [comment]
I'd try

    $scope.$on("cropme:done", function(ev, result, canvasEl) {
        if (result.originalImage.size > SIZE_LIMIT_IN_BYTES) {
            // TODO: send a notification to the user
            return $scope.$broadcast("cropme:cancel");
        }
        // TODO: upload here
    })

**Comment by divyenduz** [comment]
Let me give it a go

**Comment by standup75** [comment]
Let me know so we can close this ticket

**Comment by divyenduz** [comment]
This one works perfect.

Regards
