### ISSUE TITLE
Missing file type after uploading into server using sails js

### ISSUE THREAD

**Issue by sreeharieengayil** [standup75/cropme#36]
I have used cropme for cropping image and used this for uploading image into server using sails.js.

But file type is missing after cropping image.How to fix this issue.

Welcome any kind of help.

**Comment by sean-stanley** [comment]
You can safely assume the file type is png. What you get though for real is the raw data (blob format) of the image compressed as a png. I convert mine to jpg on the server once I've uploaded it.

**Comment by sreeharieengayil** [comment]
Thanks for your help Sean.I used to rename my file after uploading it to my server.my issue got fixed.

**Comment by standup75** [comment]
Yes, default type is png, but you can choose jpg in the type attribute
