### ISSUE TITLE
cropme:loaded event is firing once.

### ISSUE THREAD

**Issue by piupiupiu** [standup75/cropme#38]
Hi.

I need to limit uploading images of low resolution. Here is my code:
    `$scope.$on('cropme:loaded', function(e, width, height) {
                    if (width < 1600 || height < 1200) {
                        $scope.$broadcast("cropme:cancel");
                    }
    });`

It works fine with different images. However, if I try to upload the same image twice, it works just once. The second time I try to upload the same image, it is actually uploaded.
This happens because the scope.imgSrc parameter remains the same.

Also, there is a typo in the documentation: 
![Image]
(https://i.imgur.com/2MUBdqM.png)

**Comment by standup75** [comment]
Checkout latest version 0.2.10, I reseted scope.imgSrc on cancel, it should solve it

**Comment by standup75** [comment]
Can you confirm this is ok now, so we can close this?

**Comment by standup75** [comment]
Ok, closing now after a few months
