### ISSUE TITLE
API to change "Ok" | "Cancel" button text

### ISSUE THREAD

**Issue by divyenduz** [standup75/cropme#39]
Is there a way to change the text of buttons "Ok" | "Cancel" without jumping into the code ?

I want them to change from this 
![screenshot from 2015-03-18 12 12 34](https://cloud.githubusercontent.com/assets/746482/6704147/89799ae4-cd6a-11e4-8a1d-e094372a2942.png)

to this
![screenshot from 2015-03-18 12 12 38](https://cloud.githubusercontent.com/assets/746482/6704148/8d855d44-cd6a-11e4-8c6e-36bf4f71c5b8.png)

**Comment by standup75** [comment]
Added to version 0.3.1

**Comment by divyenduz** [comment]
I read a comment in my email that this was solved ? is it ?

**Comment by standup75** [comment]
Yes, I was just a little too fast and made some mistakes...
Please check version 0.3.2 and close ticket if solved

**Comment by divyenduz** [comment]
Hi there, I tried this but it did not work in 0.3.2

I used the API like this

<cropme
                  id="create_cropme"
                  okLabel="Upload image"
                  cancelLabel="Reselect another image"
                  width="550"
                  destination-width="330"
                  destination-height="200"
                  send-original="true">
              </cropme>

**Comment by standup75** [comment]
Sorry, I updated the readme, it was ok-label and cancel-label.
I also updated the demo with custom labels
No new release needed
Please close if it's ok now

**Comment by divyenduz** [comment]
Worked. Thanks again.
