### ISSUE TITLE
Could you please fix bug with select box?

### ISSUE THREAD

**Issue by AndreyKornyenko** [standup75/cropme#40]
I have a problem with "select" box:

http://storage4.static.itmages.com/i/15/0331/s_1427811905_3076036_336d561df9.png

This code is a problem:
<div class=\"overlay-border\" ng-style=\"{'top': (yCropZone - 2) + 'px', 'left': (xCropZone - 2) + 'px', 'width': widthCropZone + 'px', 'height': heightCropZone + 'px'}\"></div>

If I change it to:

<div class=\"overlay-border\" ng-style=\"{'top': (yCropZone ) + 'px', 'left': (xCropZone ) + 'px', 'width': widthCropZone + 'px', 'height': heightCropZone + 'px'}\"></div>

All works good. Could you please help me?

Thanks

**Comment by standup75** [comment]
You want it to be bigger?

**Comment by AndreyKornyenko** [comment]
No.
http://storage4.static.itmages.com/i/15/0401/h_1427877140_5974924_d47002738e.png
Do you see space between border and overlay(i marked it by yellow color)?
This bug appears in this code
http://storage4.static.itmages.com/i/15/0401/h_1427877324_5366352_0b4e3241ba.png
If you will remove "-2"  in (yCropZone - 2) + 'px' -all will work good.

Thanks

**Comment by standup75** [comment]
I am not experiencing this. Could you let me know: Which browser, which image are you using?

**Comment by Sebi55** [comment]
Hey, I have actually got the same problem. The right and bottom border is not correct. It seems like the right and bottom box are not correct in margin-top, left and their width but just by a little bit. I am using Chrome and tested also on Vivaldi so it might be on all chromium browsers. I am using jpg as image and got the width and height set to 960x400 also for the destination.

**Comment by Sebi55** [comment]
I fixed it by editing the cropme.js
Just remove the -2 on xcropzone and ycropzone.
It now works perfectly.
Why does it even use the -2?

**Comment by standup75** [comment]
This is corrected in v0.3.5
