### ISSUE TITLE
Firefox  show error Unsupported type of image?

### ISSUE THREAD

**Issue by datnq201088** [standup75/cropme#41]
On firefox browser, i fix src  It work well, but i browser file image -> error appear " Unsupported type of image"?

**Comment by divyenduz** [comment]
+1 @standup75 It is working only on Chrome. It stopped working on Firefox, Safari

**Comment by marcorivm** [comment]
I would have read the issues before use this directive :( now i am struggling with this.

**Comment by michaltowilk** [comment]
Same situation here... :( Please someone could work on this?

**Comment by pythonee** [comment]
Same situation here.

**Comment by standup75** [comment]
(finally) fixed in 0.3.3

**Comment by divyenduz** [comment]
@standup75 : 
It is not working in Linux Mint Firefox. I got the following error which is different from the error discussed in this issue ticket. Should I open a new one ?

![screenshot from 2015-07-29 11 39 37](https://cloud.githubusercontent.com/assets/746482/8951029/b45ae9cc-35e6-11e5-906d-4c1d34bc5cd2.png)
