### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by hasandogu** [standup75/cropme#44]
When I click the demo link, it gives the following:

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: cropmedemo
RequestId: 4E1B693D90C09394
HostId: LvdWqC+U+HdB+fTvheFFmb6Za9EN2PIYO3yVCc2KDxsE8AqFFBHlh7ezTzF4hSV2t4IQRBcwICg=

**Comment by standup75** [comment]
fixed
