### ISSUE TITLE
API for removing the ability to change image size

### ISSUE THREAD

**Issue by divyenduz** [standup75/cropme#45]
Note that this one is different from https://github.com/standup75/cropme/issues/30

Is it possible to disable the resize window to make it fixed ? I want that the user should only be able to upload the image and move the resize box around to choose the image part he wants BUT not be able to change the size of resize box at all.

Because resize the image causes a drop in image quality.

Thanks

**Comment by standup75** [comment]
Can't you just play with destinationHeight and destinationWidth to fix the final image resolution?

**Comment by divyenduz** [comment]
That was not the use case for me back then. Now, that requirement is finished from my end. I will close this ticket. Will generate a PR may the need be in future for me. 

Thanks for making a good library.
