### ISSUE TITLE
bower.json missing angular-route

### ISSUE THREAD

**Issue by longpham91** [standup75/cropme#48]
Hey @standup75 ,

Love this project you've been working on. Just a small reminder: You didn't add angular-route to the dependencies on bower.json, so when running the demo from localhost, the demo breaks because it's missing angular-route. Hope you can fix it soon so other people don't have the same issue.

Best regards,

Leo

**Comment by standup75** [comment]
angular-route is in the dependencies in bower.json inside the demo folder. Maybe it was not clear that you should run `npm install & bower install` inside the demo folder to run it locally, I'll add that to the readme
