### ISSUE TITLE
Add Element ID in events

### ISSUE THREAD

**Issue by magoragit** [standup75/cropme#49]
Please add element id in events (:loaded, :done).

**Comment by standup75** [comment]
Which element id? The canvas?

**Comment by voviarka** [comment]
I have 2 elements(<cropme>) on my form and need to get Id of <cropme> element from event object, when you load picture to determine which one I'm using. Does it make sense?

**Comment by standup75** [comment]
It makes sense. Note that done and progress events already have the canvas element as parameter from which you can retrieve the ID. But I will add the canvasEl to loaded and cancel. Would that work for you?

**Comment by magoragit** [comment]
Yup, go ahead, please. I need it especially for loaded one.

**Comment by voviarka** [comment]
Yup, go ahead, please. I need it especially for loaded one.

**Comment by standup75** [comment]
See https://github.com/standup75/cropme/releases/tag/0.4.0, update readme too
