### ISSUE TITLE
set image type to gif

### ISSUE THREAD

**Issue by Ads7** [standup75/cropme#53]
Is there any option to set/modify image type dynamically as per image type 
I require to upload gif [though cropper shows a gif in preview] but cropped image is of type png

**Comment by standup75** [comment]
Per the readme

#### type (optional)
Valid values are 'png' or 'jpeg' (might work with webm too, haven't tried it)

I have not tried gif, but I assume gif is not supported. 

For firefox it's unclear: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/mozGetAsFile#Specifications

For the other browsers, toDataURL is used, and you can see what types it supports by going to this page on each browser: http://kangax.github.io/jstests/toDataUrl_mime_type_test/

**Comment by Ads7** [comment]
thanks for the information
