### ISSUE TITLE
Highlighted corners

### ISSUE THREAD

**Issue by Sebi55** [standup75/cropme#54]
I would like to somehow highlight the corners while cropping to make clear that you can drag the corners and that the size is not fixed.
I tried it using pure css but since the HTML code is quite fixed I was not able to add an attribute which would just highlight the corners.
Does anyone have already such a change to the code?
If so I would appreciate some sample code for this.

**Comment by standup75** [comment]
You can add divs for the corners and style them here inside the template, inside this div
https://github.com/standup75/cropme/blob/master/scripts/directives/cropme.coffee#L48
