### ISSUE TITLE
Data not posting to PHP

### ISSUE THREAD

**Issue by aryandelhi** [standup75/cropme#55]
I'm using Cropme to crop and post image but not getting anything on server side. I'm using PHP on server side. Just printing $_POST['any variable'], but not working

I think the way I'm posting data could be wrong. Any idea?? Thanks in advance.

    $scope.$on('cropme:done', function(ev, result, cropmeEl){
						var postProfileImage = {
							request: 'profile_update',
							profile_type: 'upload_profile_image',
							user_id: window.userId,
							image: result.croppedImage,
							image_ext: result.croppedImage.type 
						};
						console.log(result.croppedImage);
						$http.post( window.url + '/rest-api/web', postProfileImage).then(function(response){ console.log(response); }, function(){});
    });

**Comment by standup75** [comment]
Many things can happen on the server side, hope you figured that one out!
