### ISSUE TITLE
Can I change the 'src' source in run-time?

### ISSUE THREAD

**Issue by nimeso** [standup75/cropme#57]
I've got my img url stored iin my $scope and it can change but the cropme DOM does not update 
eg:

html:
<cropme 
....
src={{myChangingURL}}
....
>

js:
$scope.myChangingURL = "img/myimage1.jpg";
then later on I change it to:
$scope.myChangingURL = "img/myimage2.jpg";

this won't work :(

Any ideas would be great! And thanks for all the hard work.

**Comment by standup75** [comment]
What was the issue here?
