### ISSUE TITLE
Height parameter is not respected

### ISSUE THREAD

**Issue by hughanderson4** [standup75/cropme#59]
When I set height parameter to 300, the box expands to very tall if a portrait image is selected, and stays around 300 if a landscape image is selected.  What I'm trying to do is have a consistent height regardless of what orientation image is selected.  I have tried also setting width, and not setting width.  Neither seems to matter.

**Comment by standup75** [comment]
That is true, usually, width is the constraint. I made a change in version 1.0.3
It also include your PR. Thanks for catching that.
Let me know if that works for you
